
FROM gcc:9.2

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /home/build

RUN apt-get update && apt-get install -y cmake libgtest-dev lcov && rm -rf /var/lib/apt/lists/*

CMD cmake .. && make all && make NightlyTest && make NightlyCoverage